"""Tool calling system ported from Claude Code architecture.

Provides:
- Tool base class with rich metadata (isConcurrencySafe, isReadOnly, etc.)
- build_tool() factory with safe defaults
- ToolUseContext, ToolResult, ToolCallProgress
- Tool registry with filtering, deny-rule support, pool assembly
- StreamingToolExecutor with concurrent-safe parallel execution
- run_tool_use() single-tool executor
- run_tools() batch orchestrator
- Individual tool implementations (23 tools)
"""

from aurora_core.tool.base import (
    Tool,
    ToolResult,
    ToolUseContext,
    ToolProgress,
    ToolCallProgress,
    ToolInputJSONSchema,
    ToolPermissionContext,
    ValidationResult,
    PermissionResult,
    build_tool,
    tool_matches_name,
    find_tool_by_name,
    filter_tools_by_deny_rules,
    assemble_tool_pool,
    ToolProgressData,
    BashProgress,
    ReadProgress,
    WriteProgress,
    EditProgress,
    GlobProgress,
    GrepProgress,
    WebFetchProgress,
    WebSearchProgress,
    AgentProgress,
    TaskProgress,
    Progress,
)
from aurora_core.tool.registry import (
    ToolRegistry,
    get_all_base_tools,
    get_tools,
    get_merged_tools,
)
from aurora_core.tool.executor import run_tool_use
from aurora_core.tool.streaming import StreamingToolExecutor
from aurora_core.tool.orchestrator import run_tools, partition_tool_calls
from aurora_core.tool.tools import (
    BashTool,
    ReadTool,
    WriteTool,
    EditTool,
    GlobTool,
    GrepTool,
    WebFetchTool,
    WebSearchTool,
    AgentTool,
    TaskOutputTool,
    AskUserQuestionTool,
    SkillTool,
    EnterPlanModeTool,
    ExitPlanModeTool,
    SendMessageTool,
    NotebookEditTool,
    LSPTool,
    TodoWriteTool,
    TaskCreateTool,
    TaskGetTool,
    TaskUpdateTool,
    TaskListTool,
    TaskStopTool,
)

__all__ = [
    "Tool",
    "ToolResult",
    "ToolUseContext",
    "ToolProgress",
    "ToolCallProgress",
    "ToolInputJSONSchema",
    "ToolPermissionContext",
    "ValidationResult",
    "PermissionResult",
    "build_tool",
    "tool_matches_name",
    "find_tool_by_name",
    "filter_tools_by_deny_rules",
    "assemble_tool_pool",
    "ToolProgressData",
    "BashProgress",
    "ReadProgress",
    "WriteProgress",
    "EditProgress",
    "GlobProgress",
    "GrepProgress",
    "WebFetchProgress",
    "WebSearchProgress",
    "AgentProgress",
    "TaskProgress",
    "Progress",
    "ToolRegistry",
    "get_all_base_tools",
    "get_tools",
    "get_merged_tools",
    "run_tool_use",
    "StreamingToolExecutor",
    "run_tools",
    "partition_tool_calls",
    "BashTool",
    "ReadTool",
    "WriteTool",
    "EditTool",
    "GlobTool",
    "GrepTool",
    "WebFetchTool",
    "WebSearchTool",
    "AgentTool",
    "TaskOutputTool",
    "AskUserQuestionTool",
    "SkillTool",
    "EnterPlanModeTool",
    "ExitPlanModeTool",
    "SendMessageTool",
    "NotebookEditTool",
    "LSPTool",
    "TodoWriteTool",
    "TaskCreateTool",
    "TaskGetTool",
    "TaskUpdateTool",
    "TaskListTool",
    "TaskStopTool",
]
