from typing import Any, Optional

from chatbi_core.agent.skill.base import BaseSkill


class ReportSkill(BaseSkill):
    """Format and return a structured report from the provided content."""

    @property
    def name(self) -> str:
        return "report_generation"

    @property
    def description(self) -> str:
        return (
            "Generate a structured report from analysis results. "
            "Use this to consolidate findings from multiple tools into a final formatted report."
        )

    @property
    def description_cn(self) -> str:
        return "根据分析结果生成结构化报告，整合多个工具的分析发现。"

    @property
    def parameters(self) -> dict[str, Any]:
        return {
            "type": "object",
            "properties": {
                "report_content": {
                    "type": "string",
                    "description": "The markdown or text content of the report.",
                },
                "title": {
                    "type": "string",
                    "description": "Optional title of the report.",
                },
            },
            "required": ["report_content"],
        }

    async def execute(
        self,
        report_content: str = "",
        title: Optional[str] = None,
        **kwargs: Any,
    ) -> str:
        if not report_content:
            return "No report content provided."

        header = f"# {title}\n\n" if title else ""
        return (
            f"{header}"
            f"{report_content}\n\n"
            f"---\n"
            f"*Report generated by ChatBI*"
        )
