"""Phase 5 — Knowledge V2 API layer.

RAG knowledge base API endpoints migrated from LightRAG, including:
- Document ingestion and pipeline management
- Multi-mode RAG queries (local / global / hybrid / naive / mix / bypass)
- Knowledge graph CRUD operations
- Ollama-compatible API shim
"""

from aurora_serve.knowledge.v2.schemas import (
    DeleteDocRequest,
    DocStatusResponse,
    DocumentsRequest,
    EntityCreateRequest,
    EntityMergeRequest,
    EntityUpdateRequest,
    EvaluationItemRequest,
    EvaluationRequest,
    EvaluationResponse,
    EvaluationScoreDetail,
    GraphImportEntity,
    GraphImportRelationship,
    GraphImportRequest,
    GraphImportResponse,
    GraphImportStats,
    GraphResponse,
    InsertResponse,
    InsertTextRequest,
    InsertTextsRequest,
    MergeStrategyEnum,
    OllamaChatRequest,
    OllamaGenerateRequest,
    OllamaMessage,
    OperationSummaryResponse,
    PipelineStatusResponse,
    QueryDataResponse,
    QueryRequest,
    QueryResponse,
    RelationCreateRequest,
    RelationEditRequest,
    ScanResponse,
    StatusCountsResponse,
)
from aurora_serve.knowledge.v2.extraction_routes import (
    BatchExtractRequest,
    BatchExtractResponse,
    ExtractionConfigResponse,
    ExtractionConfigUpdateRequest,
)

__all__ = [
    "BatchExtractRequest",
    "BatchExtractResponse",
    "DeleteDocRequest",
    "DocStatusResponse",
    "DocumentsRequest",
    "EntityCreateRequest",
    "EntityMergeRequest",
    "EntityUpdateRequest",
    "EvaluationItemRequest",
    "EvaluationRequest",
    "EvaluationResponse",
    "EvaluationScoreDetail",
    "ExtractionConfigResponse",
    "ExtractionConfigUpdateRequest",
    "GraphImportEntity",
    "GraphImportRelationship",
    "GraphImportRequest",
    "GraphImportResponse",
    "GraphImportStats",
    "GraphResponse",
    "InsertResponse",
    "InsertTextRequest",
    "InsertTextsRequest",
    "MergeStrategyEnum",
    "OllamaChatRequest",
    "OllamaGenerateRequest",
    "OllamaMessage",
    "OperationSummaryResponse",
    "PipelineStatusResponse",
    "QueryDataResponse",
    "QueryRequest",
    "QueryResponse",
    "RelationCreateRequest",
    "RelationEditRequest",
    "ScanResponse",
    "StatusCountsResponse",
]
